name: EditorConfig Checker

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2.0.0
      - name: Check that code complies with editorconfig
        run: editorconfig-checker
